# Documentation: https://docs.google.com/a/proteusnet.com/document/d/1B6GEpHSMAsxnn4hfh_t-1NvKqh7vHWKNyun3TOaKWM0/edit?usp=sharing
sandbox_config:
  source_site_key: demo.proteusthemes.com # key from production wordpress_sites dict
  export_site_key: xml-io.proteusthemes.com # key from sandbox wordpress_sites dict
  shared_db_name: demo_proteusthemes_com_production # this database is daily synced from production to sandbox
  wp_rsync_opts:
    root:
      - "--delete"
      - "--exclude='.git/'"
      - "--exclude='robots.txt'"
      - "--exclude='wp-config.php'"
      - "--exclude='wp-cli.yml'"
      - "--exclude='/google*.html'"
      - "--exclude='/.htaccess'"
      - "--exclude='/wc-logs/'"
      - "--exclude='/wp-content/advanced-cache.php'"
      - "--exclude='/wp-content/uploads/'"
      - "--exclude='/wp-content/cache/'"
      - "--exclude='/wp-content/plugins/wp-rocket/'"
      - "--exclude='/wp-content/plugins/js-style-swicher-*/'"
      - "--exclude='/wp-content/plugins/*-style-switcher/'"
      - "--exclude='/wp-content/plugins/pt-preview-bar/'"
      - "--exclude='/wp-content/plugins/wordpress-popup/'"
      - "--exclude='/wp-content/plugins/wp-asset-clean-up/'"
      - "--exclude='/wp-content/plugins/intercom/'"
      - "--exclude='/wp-content/mu-plugins/'"
    uploads:
      - "--delete"
      - "--ignore-existing"
      - "--exclude='.*'"
      - "--exclude='Makefile'"
  xml_paths:
    local: /tmp/xml-exports
    remote: "{{ www_root }}/artifacts.proteusthemes.com/xml-exports"

sites_to_export:
  - hairpress
  - webmarket
  - carpress
  - organique
  - readable
  - buildpress
  - mentalpress
  - cargopress
  - legalpress
  - repairpress
  - structurepress
  - beauty
  - auto
  - hammer
  - bolts
  - bolts-transport
  - bolts-factory
  - bolts-industry
  - shaka
  - buildpress-light
  - adrenaline
  - consultpress
  - buildpress-landscape
  - buildpress-rtl
  - medicpress
  - gympress
  - growthpress
  - woondershop

# replace these emails to info@example.com when importing
wp_emails:
  from:
    - 'primoz@proteusnet\.com'
    - 'info@proteusthemes\.com'
    - 'gregor\.capuder@proteusnet\.com'
    - 'jejcic\.jaka@gmail\.com'
    - 'jaka@spaka\.si'
    - 'marko\.prelec@proteusnet\.com'
  to: 'info@example.com'

# strings like API keys etc
strings_to_replace:
  - from: "{{ vault_forecastio_api_key }}"
    to: ""
  - from: "{{ vault_wcappointments_license }}"
    to: ""
  - from: "{{ vault_mc_api_key }}"
    to: ""

xmls_to_rename:
  hairpress: "hairpresswptheme"
  bolts-factory: "boltsfactory"
  bolts-industry: "boltsindustry"
  bolts-transport: "boltstransport"
  buildpress-light: "buildpresslight"
  buildpress-landscape: "buildpresslandscape"
  buildpress-rtl: "buildpressrtl"
