# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/sandbox/vault/wordpress_sites.yml

wordpress_sites:
  sandbox.proteusthemes.com:
    site_hosts:
      - canonical: sandbox.proteusthemes.com
    admin_user: proteusnet
    admin_email: noreply@proteusthemes.com
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: true
      provider: manual
      cert: ../certs/proteusthemes.com.pem
      key: ../certs/proteusthemes.com.key
    cache:
      enabled: false
  xml-io.proteusthemes.com:
    site_hosts:
      - canonical: xml-io.proteusthemes.com
    admin_user: proteusnet
    admin_email: noreply@proteusthemes.com
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: true
      provider: manual
      cert: ../certs/proteusthemes.com.pem
      key: ../certs/proteusthemes.com.key
    cache:
      enabled: false
