# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  sandbox.proteusthemes.com:
    site_hosts:
      - sandbox.proteusthemes.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://sandbox.proteusthemes.com
      wp_siteurl: http://sandbox.proteusthemes.com
      wp_env: sandbox
      db_name: example_sandbox
      db_user: example_dbuser
      db_password: example_dbpassword
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      # These CANNOT contain the characters "{%" in succession
      auth_key: "generateme"
      secure_auth_key: "generateme"
      logged_in_key: "generateme"
      nonce_key: "generateme"
      auth_salt: "generateme"
      secure_auth_salt: "generateme"
      logged_in_salt: "generateme"
      nonce_salt: "generateme"
