---
- name: Fetch data from prod server and overwrite local WP installations
  hosts: web
  sudo: yes

  roles:
    - { role: sandbox-remote, tags: [sandbox-remote] }

- name: Local actions
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  roles:
    - { role: sandbox-local, tags: [sandbox-local] }
