---
- name: Fetch data from prod server and overwrite local WP installations
  hosts: as
  sudo: yes
  roles:
    - { role: sandbox-remote, tags: [sandbox-remote] }

- name: Perform local actions on sandbox server
  hosts: sbs
  sudo: yes
  roles:
    - { role: sandbox-local, tags: [sandbox-local] }

- name: Deploy XML files
  hosts: as
  become: yes
  become_user: deployer
  tasks:
    - name: Find all XML exports
      local_action: "command find /tmp/xml-exports/ -name '*.xml'"
      register: xmls_to_transfer

    - name: Deploy latest XML files to as
      copy:
        src:  "{{ item }}"
        dest: "{{ www_root }}/artifacts.proteusthemes.com/xml-exports-new/" # TODO var
      with_items: "{{ xmls_to_transfer.stdout_lines }}"
      register: transfered_xmls

    - debug: var=transfered_xmls

    # - name: Symlink to these latest files
    #   file:
    #     src:  "{{ www_root }}/artifacts.proteusthemes.com/xml-exports-new/"
    #     dest: "/tmp/xml-exports/" # TODO var
    #   with_items: sites_to_export
