---
- name: Determine Remote User
  hosts: web
  gather_facts: false
  roles:
    - { role: remote-user, tags: [remote-user, always] }

- name: WordPress Server - Install LEMP Stack with PHP 5.6 and MariaDB MySQL
  hosts: web
  sudo: yes
  roles:
    - { role: common, tags: [common] }
    - { role: swapfile, swapfile_size: 1GB, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp }
    - { role: users, tags: [users] }
    - { role: dotfiles, tags: [dotfiles], become: yes, become_user: primoz }
    - { role: sshd, tags: [sshd] }
    - { role: mariadb, tags: [mariadb], when: not mysql_remote_database }
    - { role: ssmtp, tags: [ssmtp mail] }
    - { role: php, when: not hhvm, tags: [php] }
    - { role: hhvm, when: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: composer, tags: [composer] }
    - { role: ansible, tags: [ansible] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup] }
    - { role: wordpress-install, tags: [wordpress, wordpress-install] }
  tasks:
    - name: Copy this repo
      git:
        repo:    https://github.com/proteusthemes/pt-ops.git
        dest:    /opt/proteusnet/ops/
        version: master
      tags: after-roles

    - name: Add cron to reset every day
      become: yes
      become_user: "{{ admin_user }}"
      cron:
        name:   "reset sandbox every day"
        state:  "present"
        minute: "0"
        hour:   "8"
        job:    "ANSIBLE_NOCOLOR='1' ansible-playbook -i /opt/proteusnet/ops/hosts/sandbox_internal --vault-password-file=/opt/proteusnet/vault-key /opt/proteusnet/ops/sandbox-reset.yml > /var/log/sandbox/ansible-reset.log 2>&1"
      tags: after-roles
