---
- name: Generate self-signed certificates
  shell: >
    openssl req -subj "/CN={{ item.value.site_hosts | first }}" -new
    -newkey rsa:2048 -days 3650 -nodes -x509 -sha256
    -keyout {{ item.key }}.key -out {{ item.key }}.cert
  args:
    chdir: "{{ nginx_path }}/ssl"
    creates: "{{ item.key }}.*"
  with_dict: "{{ wordpress_sites }}"
  when: >
    item.value.ssl.enabled and item.value.site_hosts | first
    not in self_signed_domains.results | default([]) | map(attribute='stdout') | list
  notify:
    - reload nginx
