composer_keep_updated: true
composer_global_packages:
 - { name: hirak/prestissimo }
apt_cache_valid_time: 3600
apt_package_state: present
apt_security_package_state: latest
apt_dev_package_state: latest
ntp_timezone: Etc/UTC
ntp_manage_config: true
www_root: /srv/www
ip_whitelist:
  - "{{ (env == 'development') | ternary(ansible_default_ipv4.gateway, ipify_public_ip | default('')) }}"

scripts_root: "{{ www_root }}/scripts"

mariadb_mirror: ams2.mirrors.digitalocean.com
mariadb_version: "10.1"

h5bp_extra_security_enabled: false

apt_packages_custom:
  zip: "{{ apt_package_state }}"
  unzip: "{{ apt_package_state }}"
  imagemagick: "{{ apt_package_state }}"
  acl: "{{ apt_package_state }}"


# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_wordpress_sites
