# Documentation: https://docs.google.com/a/proteusnet.com/document/d/1B6GEpHSMAsxnn4hfh_t-1NvKqh7vHWKNyun3TOaKWM0/edit?usp=sharing
sandbox_config:
  source_site_key: demo.proteusthemes.com # key from production wordpress_sites dict
  export_site_key: xml-io.proteusthemes.com # key from sandbox wordpress_sites dict
  shared_db_name: demo_proteusthemes_com_production # this database is daily synced from production to sandbox

xml_paths:
  local: /tmp/xml-exports
  remote: "{{ www_root }}/artifacts.proteusthemes.com/xml-exports"

sites_to_export:
  - hairpress
  - webmarket
  - carpress
  - organique
  - readable
  - buildpress
  - mentalpress
  - cargopress
  - legalpress
  - repairpress
  - structurepress
  - beauty
  - auto
  - hammer
  - bolts
  - bolts-transport
  - bolts-factory
  - bolts-industry
  - shaka
  - buildpress-light
  - adrenaline
  - consultpress
  - buildpress-landscape
  - buildpress-rtl
  - medicpress
  - gympress
  - growthpress
  - woondershop
