# Documentation: https://docs.google.com/a/proteusnet.com/document/d/1B6GEpHSMAsxnn4hfh_t-1NvKqh7vHWKNyun3TOaKWM0/edit?usp=sharing
src_domain: "demo.proteusthemes.com" # inside {{ www_root }}
src_url: "https://{{ src_domain }}"

sb_wp_sites:
  sandbox.proteusthemes.com:
    env: # this must match the groups_vars/sandbox
      db_name: sandbox_network # TODO vault
      db_user: proteusnet
      db_password: devpw # TODO vault
      db_prefix: wpsites_
  xml-io.proteusthemes.com:
    env: # this must match the groups_vars/sandbox
      db_name: xml_io_network # TODO vault
      db_user: proteusnet
      db_password: devpw # TODO vault
      db_prefix: wpsites_

wp_rsync_opts:
  root:
    - "--delete"
    - "--exclude='.git/'"
    - "--exclude='wp-config.php'"
    - "--exclude='wp-cli.yml'"
    - "--exclude='/google*.html'"
    - "--exclude='/.htaccess'"
    - "--exclude='/wc-logs/'"
    - "--exclude='/wp-content/advanced-cache.php'"
    - "--exclude='/wp-content/uploads/'"
    - "--exclude='/wp-content/cache/'"
  uploads:
    - "--delete"
    - "--ignore-existing"
    - "--exclude='.*'"
    - "--exclude='Makefile'"

# replace these emails to info@example.com when importing
emails_to_replace:
  - 'primoz\.cigler@gmail\.com'
  - 'primoz@proteusnet\.com'
  - 'primoz\.cigler@outlook\.com'
  - 'info@proteusthemes\.com'
  - 'capuderg@gmail\.com'
  - 'jejcic\.jaka@gmail\.com'
  - 'jaka@spaka\.si'
  - 'lenagregorcic@gmail\.com'
  - 'marko\.prelec@proteusnet\.com'
