# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  demo.proteusthemes.com:
    site_hosts:
      - demo.proteusthemes.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: false
    site_title: ProteusThemes
    admin_user: admin
    admin_password: admin
    admin_email: admin@example.dev
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://demo.proteusthemes.dev
      wp_siteurl: http://demo.proteusthemes.dev
      wp_env: development
      db_name: demo_network
      db_user: root
      db_password: root
