# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  demo.proteusthemes.com:
    site_hosts:
      - demo.proteusthemes.dev
    local_path: ../www/demo.proteusthemes.com # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: ProteusThemes
    admin_user: proteusnet
    admin_password: admin
    admin_email: proteusnet@proteusthemes.dev
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://demo.proteusthemes.dev
      wp_siteurl: http://demo.proteusthemes.dev
      wp_env: development
      db_name: demo_network
      db_user: proteusnet
      db_password: devpw
      db_prefix: wpsites_
