---
- include_vars: "{{ playbook_dir }}/roles/mariadb/defaults/main.yml"
  when: "{{ mariadb_backup_dir is not defined }}"

- name: Fetch DB files
  fetch:
    src: "{{ mariadb_backup_dir }}/{{ item }}-latest.sql.gz"
    dest: "/tmp/{{ item }}.sql.gz"
    fail_on_missing: yes
    flat: yes
  with_items: "{{ shared_dbs_names }}"

- name: Rsync WP (without uploads)
  synchronize:
    src:  "{{ www_root }}/{{ sandbox_config.source_site_key }}/"
    dest: "{{ www_root }}/{{ item.key }}/"
    mode: pull
    group: no
    owner: no
    rsync_opts: "{{ wp_rsync_opts.root }}"
  with_dict: "{{ wordpress_sites }}"

- name: Rsync WP uploads
  synchronize:
    src:  "{{ www_root }}/{{ sandbox_config.source_site_key }}/wp-content/uploads/"
    dest: "{{ www_root }}/{{ item.key }}/wp-content/uploads/"
    mode: pull
    group: no
    owner: no
    rsync_opts: "{{ wp_rsync_opts.uploads }}"
  with_dict: "{{ wordpress_sites }}"
