---
- name: Fetch DB files
  fetch:
    src:             "/opt/backup/mysql/demo_network-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}.sql.gz"
    dest:            /tmp/as1_db_file.sql.gz
    fail_on_missing: yes
    flat:            yes

- name: Rsync WP (without uploads)
  synchronize:
    src:  "{{ www_root }}/{{ src_domain }}/"
    dest: "{{ www_root }}/{{ item.key }}/"
    mode: pull
    group: no
    owner: no
    rsync_opts: # TODO to var
      - "--delete"
      - "--exclude='.git/'"
      - "--exclude='wp-config.php'"
      - "--exclude='wp-cli.yml'"
      - "--exclude='/google*.html'"
      - "--exclude='/.htaccess'"
      - "--exclude='/wc-logs/'"
      - "--exclude='/wp-content/advanced-cache.php'"
      - "--exclude='/wp-content/uploads/'"
      - "--exclude='/wp-content/cache/'"
  with_dict: sb_wp_sites

- name: Rsync WP uploads
  synchronize:
    src:  "{{ www_root }}/{{ src_domain }}/wp-content/uploads/"
    dest: "{{ www_root }}/{{ item.key }}/wp-content/uploads/"
    mode: pull
    group: no
    owner: no
    rsync_opts: # TODO to var
      - "--delete"
      - "--ignore-existing"
      - "--exclude='.*'"
      - "--exclude='Makefile'"
  with_dict: sb_wp_sites
