# https://roots.io/trellis/docs/nginx-includes/#sites-templates

nginx_sites_confs:
  - src: no-default.conf.j2
  - src: ssl.no-default.conf.j2
    enabled: "{{ sites_use_ssl }}"
  - src: nginx-includes/artifacts.proteusthemes.com.conf.j2
  - src: nginx-includes/html-demo.proteusthemes.com.conf.j2
  - src: nginx-includes/unwantedhero.com.conf.j2
