---
- name: Change site owner to user
  file: path="{{ www_root }}/{{ item.key }}"
        owner="{{ web_user }}"
        group="{{ web_group }}"
        state=directory
        recurse=yes
  with_dict: wordpress_sites
