---
- include_vars: group_vars/sandbox/wordpress_sites.yml

- name: Remove old DB file
  file: |
    path='/tmp/as1_db_file.sql'
    state='absent'

- name: Unzip DB
  command: gunzip as1_db_file.sql.gz
  args:
    chdir: /tmp/

- name: Create a copy of the DB for each site
  command: cp as1_db_file.sql db-{{ item.key }}.sql
  args:
    chdir: /tmp/
  with_dict: wordpress_sites

- name: Search/replace domains in the mysqldump file
  replace: |
    dest="/tmp/db-{{ item.key }}.sql"
    regexp='demo\.proteusthemes\.com'
    replace="{{ item.key }}"
  with_dict: wordpress_sites

- name: Search/replace protocol in the mysqldump file
  replace: |
    dest="/tmp/db-{{ item.key }}.sql"
    regexp="https://({{ item.key }})"
    replace="http://\1"
  with_dict: wordpress_sites

- name: Drop old DBs
  mysql_db: |
    name={{item.value.env.db_name}}
    state=absent
  with_dict: wordpress_sites

- name: Create new DBs
  mysql_db: |
    name={{item.value.env.db_name}}
    state=present
  with_dict: wordpress_sites

- name: Import SQL to fresh DBs
  mysql_db: |
    name={{item.value.env.db_name}}
    state=import
    target="/tmp/db-{{ item.key }}.sql"
  with_dict: wordpress_sites

- name: Preform WP search-replace for the remaining strings
  command: wp search-replace 'https://demo.proteusthemes.com' 'http://{{ item.key }}' --all-tables --allow-root
  args:
    chdir: "{{ www_root }}/{{ item.key }}"
  with_dict: wordpress_sites

- name: Deactivate WP rocket
  command: wp plugin deactivate wp-rocket --network --allow-root
  args:
    chdir: "{{ www_root }}/{{ item.key }}"
  with_dict: wordpress_sites
